### ISSUE TITLE
Clear filters tags

### ISSUE THREAD

**Issue by matipretz** [Nievas2/tech-library#9]
Me gusta que los tags sean acumulativos. Quizá seria útil un botón para limpiar los tags seleccionados para facilitar la navegación entre tecnologías.

PD: Excelente proyecto!

**Comment by Nievas2** [comment]
Muchas gracias por tu consejo, ya a sido agregada la funcionalidad, esperemos te sea útil la página!!.

**Comment by Nievas2** [comment]
Muchas gracias por el aporte ya a sido agregada la funcionalidad, esperamos que la página te sea útil !!.
